name = "MadDiff"
uuid = "0873d656-25a4-4889-b982-f3e325818f6d"
version = "0.1.0"
authors = ["Klamkin, Michael <mklamkin3@gatech.edu>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
ParametricNLPModels = "1ff82034-6bb8-44a0-b51b-5c1bd563924f"

[weakdeps]
DiffOpt = "930fe3bc-9c6b-11ea-2d94-6184641e85e7"
HybridKKT = "59d292e8-f99c-4495-a4cc-613f4397570f"
MadIPM = "4406d55e-1099-4ca6-ac6a-6cf051b10024"
MadNCL = "434a0bcb-5a7c-42b2-a9d3-9e3f760e7af0"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[sources]
MadNLP = {rev = "mk/moi_param", url = "https://github.com/klamike/MadNLP.jl.git"}
ParametricNLPModels = {rev = "mk/pnlpm", url = "https://github.com/klamike/ParametricNLPModels.jl.git"}

[extensions]
DiffOptExt = ["DiffOpt", "MathOptInterface"]
HybridKKTExt = "HybridKKT"
MadIPMExt = "MadIPM"
MadNCLExt = "MadNCL"
MathOptInterfaceExt = ["MathOptInterface"]

[compat]
DiffOpt = "0.5.4"
HybridKKT = "0.2.0"
MadIPM = "0.1.3"
MadNCL = "0.1.1"
MadNLP = "0.8.12"
MathOptInterface = "1.20"
NLPModels = "0.21.8"
julia = "1.12"
